name: GA Demo CI Pipeline
on: 
  push:
    branch:
      - main
jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      # step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install npm
      - name: Install node package manager
        run: npm install

      # Step 3: Log in to Dockerhub
      - name: Login to the Dockerhub
        uses: docker/login-action@v3
        with: 
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ga-nodejs:v3 .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image 
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ga-nodejs:v3
